# _HTTP_PORT=[Puerto de exposicion del api]
# _RUN_MODE=[Modo de ejecucion del api: dev, prod, test]

#Variables de la DB
# _PGUSER=[Usuario de la base de datos]
# _PGPASSWORD=[Contraseña del usuario de la base de datos]
# _PGHOST=[URL, IP, DOMINIO o ENDPOINT de la base de datos]
# _PGPORT=[Puerto de la base de datos]
# _PGDATABASE=[Nombre de la base de datos]
# _PGSCHEME=[Esquema de la base de datos, por defecto es public]


appname = API_FINANCEUP
httpport = ${API_FINANCEUP_HTTP_PORT}
runmode = ${API_FINANCEUP_RUN_MODE}
autorender = false
copyrequestbody = true
EnableDocs = true
sslmode=disable

# DEFINICION DE VARIABLES DE ENTORNO PARA LA CONEXION A LA BASE DE DATOS

PGuser = ${API_FINANCEUP_PGUSER}
PGpass = ${API_FINANCEUP_PGPASS}
PGhost = ${API_FINANCEUP_PGHOST}
PGport = ${API_FINANCEUP_PGPORT}
PGdb = ${API_FINANCEUP_PGDB}
PGschema = ${API_FINANCEUP_PGSCHEMA}