# _HTTP_PORT=[Puerto de exposicion del api]
# _RUN_MODE=[Modo de ejecucion del api: dev, prod, test]

#Variables de la DB
# _PGUSER=[Usuario de la base de datos]
# _PGPASSWORD=[Contraseña del usuario de la base de datos]
# _PGHOST=[URL, IP, DOMINIO o ENDPOINT de la base de datos]
# _PGPORT=[Puerto de la base de datos]
# _PGDATABASE=[Nombre de la base de datos]
# _PGSCHEME=[Esquema de la base de datos, por defecto es public]


appname = API_FINANCEUP_FINANZAS
httpport = ${FINANCE_BEE_HTTP_PORT}
runmode = ${FINANCE_BEE_RUN_MODE}
autorender = false
copyrequestbody = true
EnableDocs = true
sslmode=disable
sqlconn = postgres://${FINANCE_BEE_PG_USER}:${FINANCE_BEE_PG_PASS}@${FINANCE_BEE_PG_HOST}:${FINANCE_BEE_PG_PORT}/${FINANCE_BEE_PG_DBNAME}?sslmode=disable&search_path=${FINANCE_BEE_PG_SCHEMA}

# DEFINICION DE VARIABLES DE ENTORNO PARA LA CONEXION A LA BASE DE DATOS

PGuser = ${FINANCE_BEE_PG_USER}
PGpass = ${FINANCE_BEE_PG_PASS}
PGhost = ${FINANCE_BEE_PG_HOST}
PGport = ${FINANCE_BEE_PG_PORT}
PGdb = ${FINANCE_BEE_PG_DBNAME}
PGschema = ${FINANCE_BEE_PG_SCHEMA}
