appname = Api_soporte
httpport = ${Api_soporte_HTTP_PORT}
runmode = ${Api_soporte_RUN_MODE}
autorender = false
copyrequestbody = true
EnableDocs = true

#Definicion de la variable de datos

PGuser = ${Api_soporte_PGUSER}
PGpass = ${Api_soporte_PGPASS}
PGhost = ${Api_soporte_PGHOST}
PGport = ${Api_soporte_PGPORT}
PGdb = ${Api_soporte_PGDB}
PGschema = ${Api_soporte_PGSCHEMA}


