appname = FINANCEUP_BEE
httpport = 8080
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true

PG_USER   = postgres
PG_PASS   = postgres
PG_HOST   = 127.0.0.1
PG_PORT   = 5432
PG_NAME   = FINANCEUP_BEE
PG_SCHEMA = auth