appname = FINANCEUP_BEE
httpport = ${FINANCEUP_BEE_HTTP_PORT}
runmode = ${FINANCEUP_BEE_RUN_MODE}
autorender = false
copyrequestbody = true
EnableDocs = true

PGuser = ${FINANCEUP_BEE_PGUSER}
PGpass = ${FINANCEUP_BEE_PGPASS}
PGhost = ${FINANCEUP_BEE_PGHOST}
PGport = ${FINANCEUP_BEE_PGPORT}
PGdb = ${FINANCEUP_BEE_PGDB}
PGschema = ${FINANCEUP_BEE_PGSCHEMA}

