appname = FINANCEUP_BEE
httpport = ${FINANCEUP_BEE_PORT}
runmode = ${FINANCEUP_BEE_RUN_MODE}
autorender = false
copyrequestbody = true
EnableDocs = true




appname = FINANCEUP_BEE
httpport = 8080
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = postgres://postgres:postgres@127.0.0.1:5432/FINANCEUP_BEE?sslmode=disable&search_path=auth
