appname = FINANCEUP_BEE
httpport = ${FINANCEUP_BEE_PORT}
runmode = ${FINANCEUP_BEE_RUN_MODE}
autorender = false
copyrequestbody = true
EnableDocs = true

#DEFINICION DE VARIABLES DE CONEXION A DB

PGuser = postgres
PGpass = postgres
PGhost = 127.0.0.1
PGport = 5432
PGdb = bee_financeup
PGschema = negocio
