appname = FINANCEUP_BEE
httpport = 8080
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = postgres://postgres:postgres@127.0.0.1:5432/bee_financeup?sslmode=disable&search_path=negocio


PGuser = ${FINANCEUP_BEE_PGUSER}
PGpass = ${FINANCEUP_BEE_PGPASS}
PGhost = ${FINANCEUP_BEE_PGHOST}
PGport = ${FINANCEUP_BEE_PGPORT}
PGdb = ${FINANCEUP_BEE_PGDB}
PGschema = ${FINANCEUP_BEE_PGSCHEMA}